version: "3.9"
services:
  backend:
    build:
      context: ./beachappbackend
    image: local/beachappbackend
    ports:
      - "8080:8080"
#    volumes:
#      - ./src/main/resources/emailMessage.json:/src/main/resources/emailMessage.json
#      - ./src/main/resources/forecasts:/src/main/resources/forecasts
#      - ./src/main/resources/confirmationMessage.json:/src/main/resources/confirmationMessage.json


  frontend:
    build:
      context: ./beach-app
    image: local/beach-app
    ports:
      - "3000:3000"

  postgres:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
#      - ./postgres-data:/var/lib/postgresql/data #used if you want to maintain data across start up and shut down. Note volumes are execute in alphabetical order
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/hawaii_beaches.sql:/docker-entrypoint-initdb.d/hawaii_beaches.sql
